apiVersion: v1
kind: Service
metadata:
  name: argocd-app-service
  namespace: argocd
spec:
  type: ClusterIP  # NodePort 대신 ClusterIP로 변경
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: argocd
